### ISSUE TITLE
Is the configuration file actually being used right now?

### ISSUE THREAD

**Issue by jacebrowning** [pyupio/pyup#132]
The documentation says I can create a `.pyup.yml` to control which requirements files are updated as I did [here](https://github.com/jacebrowning/template-python-demo/blob/b69e76005999dfaa52eb6888cc2974c95e6ad1d4/.pyup.yml):

```yml
search: False

requirements:
  - requirements.txt

branch: python2-pytest
```

but @pyup-bot still created PRs for all my nested requirements files:

![screen shot 2016-10-21 at 5 07 20 pm](https://cloud.githubusercontent.com/assets/939501/19611676/da3b9d44-97b0-11e6-840f-79b50f7e3bde.png)

Are configuration files **actually** supported right now?

**Comment by jayfk** [comment]
> Are configuration files actually supported right now?

Yes! My first guess is that the bot got somehow mixed up with the branches and tries to fetch the config file from the wrong branch.

I'll probably have time on monday to go through the logs to check what exactly is happening. If you want the PRs to be removed, you'll have to deactivate the repo and close them manually (the bot will re create them if not).

If it's okay to leave them open, just leave them there for the weekend until this is sorted out.

**Comment by jacebrowning** [comment]
I will leave them open on [that project](https://github.com/jacebrowning/template-python-demo) , which is simply a project template.

FWIW, I also enabled this bot on [another project](https://github.com/jacebrowning/memegen/commit/641c7e8dab38f1acd349b06b98589812df188241) that does use `master` as its default branch and saw a similar result (extra PRs) using this configuration:

```yml
search: False

requirements:
  - requirements.txt:
      pin: True
  - requirements/ci.txt:
      pin: False
  - requirements/dev.txt:
      pin: False
```
