### ISSUE TITLE
Bot is updating unpinned deps when configured to ignore them

### ISSUE THREAD

**Issue by benjaoming** [pyupio/pyup#319]
Please LMK if I'm doing something wrong, but this didn't use to happen IIRC...

Example PR:

https://github.com/learningequality/kolibri/pull/4145/files

Configuration:

https://github.com/learningequality/kolibri/blob/develop/.pyup.yml#L29

**Comment by Jwomers** [comment]
@benjaoming this does seem incorrect, let me look into it

**Comment by benjaoming** [comment]
This also relates to the following PR:

https://github.com/learningequality/kolibri/pull/4146

Which should not have occurred since it was configured not to:
```
  - requirements/pipeline.txt:
      # This is only used on buildkite for some build stuff
      # so not very important
      update: False
      pin: False
```
