### ISSUE TITLE
Bot looking in files it shouldn't

### ISSUE THREAD

**Issue by jonodrew** [pyupio/pyup#333]
I'm having an issue configuring the bot. Our config file looks like this:

```
schedule: "every day"
search: False

requirements:
  - requirements-app.txt:
      update: all
      pin: True
  - requirements-dev.txt:
      update: all
      pin: True

pr_prefix: "PyUp - "
```

but the bot is [still looking in requirements.txt](https://github.com/alphagov/digitalmarketplace-admin-frontend/pull/446/files)

Is my config right? How can I ensure it ignores `requirements.txt?` We've tried removing and re-adding the repo.
