### ISSUE TITLE
Moving to setup.cfg + adding a .pyup.yml breaks WebUI

### ISSUE THREAD

**Issue by cooperlees** [pyupio/pyup#350]
I am unsure what my error is to cause the PyUP Web UI to render unusable (screenshot attached). I might try reversing the logic to only `update: False` on setup.cfg

I can't remove the `.pyup.yml` as I don't want setup.cfg to have it's dependencies updated / pinned.

What's my best way forward? This has also stopped any PRs being made. So I am sure my `.yml` is at fault here.
- Said `.pyup.yml`: https://github.com/pypa/bandersnatch/blob/master/.pyup.yml
Original `yml` - Before any PRs:
```
search: False
update: all

requirements:
  - requirements_docs.txt:
    update: all
    pin: True
  - requirements_test.txt:
    update: all
    pin: True
  - requirements.txt:
    update: all
    pin: True

assignees:
  - cooper
```

![Screen Shot 2019-06-18 at 6 11 50 AM](https://user-images.githubusercontent.com/3005596/59685264-a5884480-9190-11e9-91a6-4e3005b0be2b.png)
