### ISSUE TITLE
PyUp not issuing PRs on my private repo

### ISSUE THREAD

**Issue by jetheurer** [pyupio/pyup#351]
Hi folks,

I've been trying to get in touch with support@pyup.io, but with no luck.  Can someone help me troubleshoot pyup on my private repository?

At the moment, my yml looks like this:

```yml
update: all
branch: master
schedule: "every day"
search: True
requirements:
  - requirements.txt:
    update: all
    pin: true
```

Cheers,

Liz
