### ISSUE TITLE
Path to requirements file contains non-alphanumeric characters causes server errors

### ISSUE THREAD

**Issue by martinm82** [pyupio/pyup#355]
I have created a cookiecutter template for Python projects. It is in general not a Python project but the templates generates one. So inside the template I have a requirements.txt file that contains several pip dependencies that I would like to be scanned by the pyup bot.

For that purpose I have created a config file: https://github.com/tomtom-international/cookiecutter-python/blob/master/.pyup.yml#L20

```
requirements:
  - "{{cookiecutter.project_name}}/requirements_dev.txt":
    # update all dependencies and pin them
    update: all
    pin: True
```

It seems that pyup does not like if the path contains non-alphanumeric characters in the path to the requirements file and causes some internal server errors:

https://pyup.io/account/repos/github/tomtom-international/cookiecutter-python/settings/

```
500 Internal Server Error
An error has occurred on this page. We are probably already working on the problem, so please try again later.
```

Is this something that is not supported or am I missing something. 

Thanks for your help.
