### ISSUE TITLE
Pyup cant find a requirements.txt file when there are brackets in the name

### ISSUE THREAD

**Issue by agconti** [pyupio/pyup#369]
# Problem 
Pyup tells me in the dashboard that it can't find my `requirements.txt` file. 

### Context
I run an open source project called [django-cookiecutter-rest](https://github.com/agconti/cookiecutter-django-rest). It's a project template for Django apps. Because of that, it uses bracketed template variables in the project's folder names.  Pyupbot is unable to find my requirements.txt file at: `{{cookiecutter.github_repository_name}}/requirements.txt`.

Here's my [.pyup.yml](https://github.com/agconti/cookiecutter-django-rest/blob/master/.pyup.yml) config:
```yaml
update: all
pin: True
branch: master

requirements:
  - /{/{cookiecutter.github_repository_name/}/}/requirements.txt

schedule: "every day"
search: True
label_prs: update
assignees:
- agconti
```

I've tried a few ways to specify the file but none have worked yet: 
- /{/{cookiecutter.github_repository_name/}/}/requirements.txt
- "{{cookiecutter.github_repository_name}}/requirements.txt"
- {{cookiecutter.github_repository_name}}/requirements.txt

Thanks for your help!
